import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
// By default, the app generated by ng init will include the FormsModule, here we’re requiring the ReactiveFormsModule as well
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';
// Include the three components we created
import {routing, appRoutingProviders} from './app.routing';
import { FormValidationComponent } from './app.formvalidations.component';
import  {HomeComponent} from './home.component';
import { AboutComponent} from './about.component'
import {FormsComponent} from './forms.component';
import {LoginComponent} from './login.component';


@NgModule({
    declarations: [
    AppComponent,
    FormValidationComponent,
    AboutComponent,
    HomeComponent,
    FormsComponent,
    LoginComponent

    ],
    imports: [
    BrowserModule,
    FormsModule,
    routing,
    ReactiveFormsModule,
    HttpModule
    ],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule { }